/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    //{
    //  type: 'doc',
    //  id: 'intro',
    //  label: 'Overview',
    //},
    {
      type: 'category',
      label: 'GETTING STARTED',
      className: 'categoryItem',
      items: [
        'intro',
        'vector-search',
        'quickstart',
        'interfaces',
        'web-ui',
          ]
    },
    {
      type: 'category',
      label: 'USER MANUAL',
      className: 'categoryItem',
      items: [
        {
          type: 'category',
          label: 'Concepts',
          className: 'categoryItem',
          items: [
            'collections',
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'TUTORIALS',
      className: 'categoryItem',
      items: [
            'tutorial-vector-search',
      ]
    },
  ],
};

module.exports = sidebars;

//module.exports = {
//  myAutogeneratedSidebar: [
//    {
//      type: 'autogenerated',
//      dirName: '.', // '.' means the current docs folder
//    },
//  ],
//};
