/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    //{
    //  type: 'doc',
    //  id: 'intro',
    //  label: 'Overview',
    //},
    'intro',
    'vector-search',
    {
      type: 'category',
      label: 'GETTING STARTED',
      className: 'categoryItem',
      items: [
        'quickstart',
        'interfaces',
        'web-ui',
          ]
    },
    {
      type: 'category',
      label: 'USER MANUAL',
      className: 'categoryItem',
      items: [
        {
          type: 'category',
          label: 'Concepts',
          className: 'categoryItem',
          items: [
            'collections',
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'TUTORIALS',
      className: 'categoryItem',
      link: {
        type: 'generated-index',
        title: 'Tutorials',
        description: 'Master vector search with Cortex through comprehensive documentation, structured courses, and hands-on tutorials.',
        slug: '/category/tutorials',
        keywords: ['guides'],
        },
        items: [
          {
            type: 'category',
            label: 'Vector Search Basics',
            className: 'categoryItem',
            items: [
                  'semantic-search-101',
            ]
          },
          {
            type: 'category',
            label: 'Advanced Retrieval',
            className: 'categoryItem',
            items: [
                  'multivector',
            ]
          },
          {
            type: 'category',
            label: 'Using the Database',
            className: 'categoryItem',
            items: [
                  'bulk-upload-vectors',
            ]
          },
      ]
    },
  ],
};

module.exports = sidebars;

//module.exports = {
//  myAutogeneratedSidebar: [
//    {
//      type: 'autogenerated',
//      dirName: '.', // '.' means the current docs folder
//    },
//  ],
//};
